source = ~/.config/omarchy/current/theme/hyprlock.conf

$font = CaskaydiaMono Nerd Font

general {
    hide_cursor = false
}

background {
    monitor =
    path = ~/.config/omarchy/current/background
    blur_passes = 2
    color = $color
}

label {
    monitor =
    text = $TIME
    color = $font_color
    font_size = 90
    font_family = $font
    position = 30, -150
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B de %Y")"
    color = $font_color
    font_size = 25
    font_family = $font
    position = 30, -300
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 400, 75
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = false
    # placeholder_text = <span foreground="##DCD2F0">󰌾  Logged in as <span 
    placeholder_text = <span foreground="##DCD2F0">󰌾  Autenticado como <span foreground="##8C50C8">$USER</span></span>
    hide_input = false
    check_color = $check_color
    fail_color = rgba(255, 85, 85, 1.0)
    # fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_text = <i>Tentativas: <b>$ATTEMPTS</b></i>
    capslock_color = rgba(241, 250, 140, 1.0)
    position = 0, -85
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
}
