services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    network_mode: "host"
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    entrypoint: ["ngrok"]
    command: http --domain=${NGROK_DOMAIN} 80
